### ISSUE TITLE
Use .hgt files from sonny.4lima.de

### ISSUE THREAD

**Issue by scriptPilot** [shred86/Ortho4XP#30]
Using the default installer and try to create some tiles in the Alps, I experience issues with the 3D mesh. It can be fixed by downloading before the .hgt files from sonny.4lima.de

Would be great to let Ortho4XP do this automatically.

**Comment by scriptPilot** [comment]
Example **zOrtho4XP_+47+012**

**Comment by shred86** [comment]
I just pushed version 1.40.05 which fixes an issue with Viewfinderspanoramas. I think this fixes some of those issues in certain regions.

I think it would be nice to add Sonny's LIDAR data as an option but I'm not sure if it's possible since all of the elevation files are hosted on Google Drive. Maybe someone has a better idea but there's no easy way I can think of to make this work. Perhaps using a web scrapper like Beautiful Soup could work but I think it would take quite a bit of effort. If all of the elevation files were hosted on a "normal" web server and the download links were organized in a logical pattern, it would be much easier to implement.

Unfortunately this isn't something I will be able to do with how the data is hosted now but I'll certainly keep this open for any ideas/discussions since I do think it would be a nice addition.

**Comment by scriptPilot** [comment]
Alright, thanks for the feedback and implementation of that fix!
